version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: tgshop-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tgshop
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # MinIO S3 Storage
  minio:
    image: minio/minio:latest
    container_name: tgshop-minio-dev
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data-dev:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  # Create MinIO bucket
  createbuckets:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_started
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO to be ready...';
      until /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin; do
        echo 'MinIO is not ready yet, waiting...';
        sleep 2;
      done;
      echo 'MinIO is ready, creating bucket...';
      /usr/bin/mc mb myminio/tgshop || true;
      /usr/bin/mc anonymous set public myminio/tgshop;
      echo 'Bucket setup complete';
      exit 0;
      "

volumes:
  postgres-data-dev:
  minio-data-dev:

networks:
  default:
    name: tgshop-network-dev

